[package]
name = "schedule_maker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
ics = "0.5"
chrono = "0.4"
itertools = "0.14.0"

